[project]
name = "pdf-embedding"
version = "0.1.0"
description = "Simple example for cocoindex: build embedding index based on local PDF files."
requires-python = ">=3.10"
dependencies = [
    "cocoindex>=0.1.20",
    "python-dotenv>=1.0.1",
    "llama-cloud-services>=0.6.9",
]
